language: python
python:
  - "3.6"
env:
  - TRAVIS_NODE_VERSION="4"
install:
  - pip install -r requirements/local.txt
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - npm install -g yarn
  - yarn global add babel-cli
  - yarn global add node-sass
  - yarn
script: pytest
